### ISSUE TITLE
Add bug reporting tool

### ISSUE THREAD

**Issue by mobinni** [rangle/react-native-example#5]
When the app crashes there has to be reporting mechanism that tracks and logs crashes from the app. 
- [ ] Fabric

**Comment by relaxedtomato** [comment]
It would be useful to have JS logs reported - I know we can get the native logs easily.

**Comment by relaxedtomato** [comment]
We are using BuddyBuild for the starter, should we stick with Fabric  (general reporting SDK not tied to CI/CD) for both development and production so we only have to integrate one SDK?

**Comment by mobinni** [comment]
I personally prefer fabric since it's an industry standard so I think we should stick to it
