### ISSUE TITLE
Add CI/CD 

### ISSUE THREAD

**Issue by mobinni** [rangle/react-native-example#6]
Add the ability to run continuous deployment and continuous integration.

- [x] Circle CI for unit testing
- [x] Buddy Build for continuous deployment
- [ ] Add build numbers to build

**Comment by relaxedtomato** [comment]
Dylan was able to get unit test working on BuddyBuild with the RN-MobilePOC: https://github.com/rangle/ReactNativeMobilePOC/pull/93
Not sure if this is a better approach - it will save us an extra build step though.

**Comment by relaxedtomato** [comment]
Also - this is something you mentioned. Adding build numbers to the app would be super useful.
